Test: Fixed the issue that coveralls was not found in the test workflow on MacOS
with Python 3.9-3.11, by running it without login shell.
