-
    name: pywbem.ConnectionError due to requests.ConnectionError
    description: GetInstance raises pywbem.ConnectionError because requests raises ConnectionError
    pywbem_request:
        url: http://acme.com:80
        creds:
            - username
            - password
        namespace: root/cimv2
        timeout: 5
        debug: false
        operation:
            pywbem_method: GetInstance
            InstanceName:
                pywbem_object: CIMInstanceName
                classname: PyWBEM_Person
                keybindings:
                    Name: Fritz
            LocalOnly: false
    pywbem_response:
        exception: ConnectionError
    http_request:
        verb: POST
        url: http://acme.com:80/cimom
        headers:
            CIMOperation: MethodCall
            CIMMethod: GetInstance
            CIMObject: root/cimv2
        data: >
            <?xml version="1.0" encoding="utf-8" ?>
            <CIM CIMVERSION="2.0" DTDVERSION="2.0">
              <MESSAGE ID="1001" PROTOCOLVERSION="1.0">
                <SIMPLEREQ>
                  <IMETHODCALL NAME="GetInstance">
                    <LOCALNAMESPACEPATH>
                      <NAMESPACE NAME="root"/>
                      <NAMESPACE NAME="cimv2"/>
                    </LOCALNAMESPACEPATH>
                    <IPARAMVALUE NAME="InstanceName">
                      <INSTANCENAME CLASSNAME="PyWBEM_Person">
                        <KEYBINDING NAME="Name">
                          <KEYVALUE VALUETYPE="string" TYPE="string">Fritz</KEYVALUE>
                        </KEYBINDING>
                      </INSTANCENAME>
                    </IPARAMVALUE>
                    <IPARAMVALUE NAME="LocalOnly">
                      <VALUE>FALSE</VALUE>
                    </IPARAMVALUE>
                  </IMETHODCALL>
                </SIMPLEREQ>
              </MESSAGE>
            </CIM>
    http_response:
        exception: requests_connection_error
-
    name: pywbem.TimeoutError due to requests.ReadTimeout
    description: GetInstance raises pywbem.TimeoutError because requests raises ReadTimeout
    pywbem_request:
        url: http://acme.com:80
        creds:
            - username
            - password
        namespace: root/cimv2
        timeout: 5
        debug: false
        operation:
            pywbem_method: GetInstance
            InstanceName:
                pywbem_object: CIMInstanceName
                classname: PyWBEM_Person
                keybindings:
                    Name: Fritz
            LocalOnly: false
    pywbem_response:
        exception: TimeoutError
    http_request:
        verb: POST
        url: http://acme.com:80/cimom
        headers:
            CIMOperation: MethodCall
            CIMMethod: GetInstance
            CIMObject: root/cimv2
        data: >
            <?xml version="1.0" encoding="utf-8" ?>
            <CIM CIMVERSION="2.0" DTDVERSION="2.0">
              <MESSAGE ID="1001" PROTOCOLVERSION="1.0">
                <SIMPLEREQ>
                  <IMETHODCALL NAME="GetInstance">
                    <LOCALNAMESPACEPATH>
                      <NAMESPACE NAME="root"/>
                      <NAMESPACE NAME="cimv2"/>
                    </LOCALNAMESPACEPATH>
                    <IPARAMVALUE NAME="InstanceName">
                      <INSTANCENAME CLASSNAME="PyWBEM_Person">
                        <KEYBINDING NAME="Name">
                          <KEYVALUE VALUETYPE="string" TYPE="string">Fritz</KEYVALUE>
                        </KEYBINDING>
                      </INSTANCENAME>
                    </IPARAMVALUE>
                    <IPARAMVALUE NAME="LocalOnly">
                      <VALUE>FALSE</VALUE>
                    </IPARAMVALUE>
                  </IMETHODCALL>
                </SIMPLEREQ>
              </MESSAGE>
            </CIM>
    http_response:
        exception: requests_read_timeout
-
    name: pywbem.TimeoutError due to requests.RetryError
    description: GetInstance raises pywbem.TimeoutError because requests raises RetryError
    pywbem_request:
        url: http://acme.com:80
        creds:
            - username
            - password
        namespace: root/cimv2
        timeout: 5
        debug: false
        operation:
            pywbem_method: GetInstance
            InstanceName:
                pywbem_object: CIMInstanceName
                classname: PyWBEM_Person
                keybindings:
                    Name: Fritz
            LocalOnly: false
    pywbem_response:
        exception: TimeoutError
    http_request:
        verb: POST
        url: http://acme.com:80/cimom
        headers:
            CIMOperation: MethodCall
            CIMMethod: GetInstance
            CIMObject: root/cimv2
        data: >
            <?xml version="1.0" encoding="utf-8" ?>
            <CIM CIMVERSION="2.0" DTDVERSION="2.0">
              <MESSAGE ID="1001" PROTOCOLVERSION="1.0">
                <SIMPLEREQ>
                  <IMETHODCALL NAME="GetInstance">
                    <LOCALNAMESPACEPATH>
                      <NAMESPACE NAME="root"/>
                      <NAMESPACE NAME="cimv2"/>
                    </LOCALNAMESPACEPATH>
                    <IPARAMVALUE NAME="InstanceName">
                      <INSTANCENAME CLASSNAME="PyWBEM_Person">
                        <KEYBINDING NAME="Name">
                          <KEYVALUE VALUETYPE="string" TYPE="string">Fritz</KEYVALUE>
                        </KEYBINDING>
                      </INSTANCENAME>
                    </IPARAMVALUE>
                    <IPARAMVALUE NAME="LocalOnly">
                      <VALUE>FALSE</VALUE>
                    </IPARAMVALUE>
                  </IMETHODCALL>
                </SIMPLEREQ>
              </MESSAGE>
            </CIM>
    http_response:
        exception: requests_retry_error
-
    name: pywbem.ConnectionError due to requests.HTTPError
    description: GetInstance raises pywbem.ConnectionError because requests raises HTTPError
    pywbem_request:
        url: http://acme.com:80
        creds:
            - username
            - password
        namespace: root/cimv2
        timeout: 5
        debug: false
        operation:
            pywbem_method: GetInstance
            InstanceName:
                pywbem_object: CIMInstanceName
                classname: PyWBEM_Person
                keybindings:
                    Name: Fritz
            LocalOnly: false
    pywbem_response:
        exception: ConnectionError
    http_request:
        verb: POST
        url: http://acme.com:80/cimom
        headers:
            CIMOperation: MethodCall
            CIMMethod: GetInstance
            CIMObject: root/cimv2
        data: >
            <?xml version="1.0" encoding="utf-8" ?>
            <CIM CIMVERSION="2.0" DTDVERSION="2.0">
              <MESSAGE ID="1001" PROTOCOLVERSION="1.0">
                <SIMPLEREQ>
                  <IMETHODCALL NAME="GetInstance">
                    <LOCALNAMESPACEPATH>
                      <NAMESPACE NAME="root"/>
                      <NAMESPACE NAME="cimv2"/>
                    </LOCALNAMESPACEPATH>
                    <IPARAMVALUE NAME="InstanceName">
                      <INSTANCENAME CLASSNAME="PyWBEM_Person">
                        <KEYBINDING NAME="Name">
                          <KEYVALUE VALUETYPE="string" TYPE="string">Fritz</KEYVALUE>
                        </KEYBINDING>
                      </INSTANCENAME>
                    </IPARAMVALUE>
                    <IPARAMVALUE NAME="LocalOnly">
                      <VALUE>FALSE</VALUE>
                    </IPARAMVALUE>
                  </IMETHODCALL>
                </SIMPLEREQ>
              </MESSAGE>
            </CIM>
    http_response:
        exception: requests_http_error
-
    name: pywbem.ConnectionError due to requests.SSLError
    description: GetInstance raises pywbem.ConnectionError because requests raises SSLError
    pywbem_request:
        url: http://acme.com:80
        creds:
            - username
            - password
        namespace: root/cimv2
        timeout: 5
        debug: false
        operation:
            pywbem_method: GetInstance
            InstanceName:
                pywbem_object: CIMInstanceName
                classname: PyWBEM_Person
                keybindings:
                    Name: Fritz
            LocalOnly: false
    pywbem_response:
        exception: ConnectionError
    http_request:
        verb: POST
        url: http://acme.com:80/cimom
        headers:
            CIMOperation: MethodCall
            CIMMethod: GetInstance
            CIMObject: root/cimv2
        data: >
            <?xml version="1.0" encoding="utf-8" ?>
            <CIM CIMVERSION="2.0" DTDVERSION="2.0">
              <MESSAGE ID="1001" PROTOCOLVERSION="1.0">
                <SIMPLEREQ>
                  <IMETHODCALL NAME="GetInstance">
                    <LOCALNAMESPACEPATH>
                      <NAMESPACE NAME="root"/>
                      <NAMESPACE NAME="cimv2"/>
                    </LOCALNAMESPACEPATH>
                    <IPARAMVALUE NAME="InstanceName">
                      <INSTANCENAME CLASSNAME="PyWBEM_Person">
                        <KEYBINDING NAME="Name">
                          <KEYVALUE VALUETYPE="string" TYPE="string">Fritz</KEYVALUE>
                        </KEYBINDING>
                      </INSTANCENAME>
                    </IPARAMVALUE>
                    <IPARAMVALUE NAME="LocalOnly">
                      <VALUE>FALSE</VALUE>
                    </IPARAMVALUE>
                  </IMETHODCALL>
                </SIMPLEREQ>
              </MESSAGE>
            </CIM>
    http_response:
        exception: requests_ssl_error
